const projectsData = {
    "VERITAS": {
        tagline: "Decentralized, Offline-First Misinformation Detection for the Edge.",
        content: `<h3>The Challenge</h3><p>In high-latency environments (like rural India or 3G networks), traditional cloud-based fact-checking is too slow (>1000ms), compromises user privacy by sending browsing data to central servers, and is inaccessible to 450M+ Indians lacking high-speed internet.</p><h3>The Architecture</h3><p>Veritas moves the intelligence from the Cloud to the Client. I optimized a DistilBERT Transformer model specifically for browser-based inference. By implementing Dynamic Int8 Quantization and leveraging the ONNX Runtime, I reduced the model size from ~400MB to 64.45MB without losing server-grade accuracy.</p><h3>Technical Highlights</h3><ul><li><strong>Ultra-Low Latency:</strong> Achieved ~23ms CPU inference locally, making it 20x faster than cloud API calls.</li><li><strong>Privacy-Centric:</strong> Zero Egress—no user data ever leaves the local environment.</li><li><strong>Web-Native Inference:</strong> Built using transformers.js for seamless integration into a production browser extension.</li></ul><p><strong>Tech Stack:</strong> DistilBERT, ONNX, Transformers.js, Optimum, JavaScript.</p>`
    },
    "EdgeDev": {
        tagline: "Architectural Hardening for the Digital Frontier.",
        content: `<h3>The Story</h3><p>Forged in the Teliamura Reserved Forest (Tripura, India), this project was built for developers operating under "Adversarial Network Conditions." It addresses extreme scarcity: 4G mobile hotspots, daily power grid cycles, and a strict 2GB daily data limit.</p><h3>The Solution</h3><p>EdgeDev is a bespoke hardening protocol for VS Code. It silences the "telemetric noise" of modern IDEs to preserve the most limited resource: Bandwidth.</p><h3>Technical Highlights</h3><ul><li><strong>Bandwidth Integrity:</strong> Hard-disables background telemetry, non-consensual extension updates, and automatic TypeScript type acquisition.</li><li><strong>Git Fetch Suppression:</strong> Prevents background repository polling to stop "hidden" data leaks.</li><li><strong>The Academic Palette:</strong> Custom high-contrast theme (Espresso/Deep Black) designed specifically to reduce visual noise and minimize power draw on battery reserves.</li><li><strong>Efficiency:</strong> Saves ~50MB - 80MB of data per coding session.</li></ul><p><strong>Tech Stack:</strong> VS Code Extension API, CSS (Custom Theming), System-level Network Protocols.</p>`
    },
    "Bhai-Lang": {
        tagline: "A Hinglish Programming Language for Desi Developers.",
        content: `<h3>The Concept</h3><p>Writing print() is too mainstream. Built on the idea that "Bhai, code toh aise likhte hain!", this project creates a relatable coding experience for developers who think in Hinglish.</p><h3>The Logic</h3><p>Built as an interpreter in Python, it maps traditional logic to local Indian slang, making it the only language where bhai bol("Namaste, duniya!"); is valid syntax.</p><h3>Technical Highlights</h3><ul><li><strong>Custom Syntax Tree:</strong> Implements standard loops (jab tak bhai), variables (bhai ye hai), and entry points (hi bhai).</li><li><strong>Roast-Driven Error Messages:</strong> Features a "Loving Roast" system for debugging. (e.g., “Maths class mein soye the kya?” for division by zero).</li><li><strong>Functionality:</strong> Supports Fibonacci sequences, FizzBuzz challenges, and basic calculators.</li></ul><p><strong>Tech Stack:</strong> Python (Core Interpreter), Git, Regex.</p>`
    },
    "Calyx": {
        tagline: "The Augmented Intelligence Harvest Layer.",
        content: `<h3>The Concept</h3><p>"The human mind is a garden. Calyx is the soil." This is a local prototype for an "Augmented Intelligence" system that treats memory as a network of connections rather than a list of files.</p><h3>The Architecture</h3><p>It uses a local Reflection Engine to process your thoughts and notes, mapping them into a persistent Insight Graph to reveal connections you didn’t know existed.</p><h3>Technical Highlights</h3><ul><li><strong>Semantic Memory:</strong> Builds an evolving memory of connections by analyzing the intent and emotional tone of user inputs.</li><li><strong>Smart Concept Retrieval:</strong> Search your knowledge base by concept or mood rather than exact keywords.</li><li><strong>Modular Storage:</strong> Uses user_knowledge.json and insights_store.json for lightweight, non-relational local data management.</li></ul><p><strong>Tech Stack:</strong> Python, Streamlit, NLP Intent Parser, Custom Insight Graph Engine.</p>`
    },
    "Echo_Aid": {
        tagline: "Real-Time Emotion-Aware Speech Companion.",
        content: `<h3>The Purpose</h3><p>An "AI that listens between the lines." Echo_Aid is a mental wellness tool designed to help users recognize their own patterns of stress and vocal tone in real-time.</p><h3>The Logic</h3><p>Built to work fully offline to respect user privacy, the app listens to your voice and classifies emotional states (calm, anxious, happy, tired) to provide gentle textual feedback.</p><h3>Technical Highlights</h3><ul><li><strong>Real-time Transcription:</strong> Uses a local voice_listener.py to capture and process audio streams instantly.</li><li><strong>Sentiment Trends:</strong> Visualizes emotional patterns over time using a dedicated mood_tracker.py.</li><li><strong>Empathetic UX:</strong> Responds with encouraging feedback like "Your tone feels calmer today" to promote mindful communication.</li></ul><p><strong>Tech Stack:</strong> Python, Streamlit, speech_recognition, Sentiment Analysis Modules.</p>`
    },
    "Border Incident Reporter": {
        tagline: "Real-Time Incident Logging for Security Personnel.",
        content: `<h3>The Solution</h3><p>A high-speed incident logging system designed for border security personnel to track breaches and suspicious activities under pressure. The goal was to ensure reporting could happen in under 30 seconds.</p><h3>Technical Highlights</h3><ul><li><strong>GPS Auto-Capture:</strong> Automatic location tagging for all reports to ensure accurate field intelligence.</li><li><strong>Intermittent Sync:</strong> Features offline capability to ensure logs are saved even when connection to the command center is lost.</li><li><strong>Severity Management:</strong> Categorizes events from Low to Critical with photo evidence attachments.</li><li><strong>Data Export:</strong> Generates CSV reports and visualizes incidents on a real-time command center dashboard using Leaflet.js.</li></ul><p><strong>Tech Stack:</strong> Flask (Backend), SQLite/PostgreSQL, Leaflet.js, Vanilla JavaScript.</p>`
    },
    "Safe_steps": {
        tagline: "Disaster Route Finder & Emergency Shelter Locator.",
        content: `<h3>The Problem</h3><p>During floods or storms,
